# Generated by Django 5.1.6 on 2025-02-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionCat', models.CharField(max_length=255)),
                ('obsCat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaccion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('afectacion', models.TextField()),
                ('consecutivo', models.CharField(max_length=255)),
                ('obsDocumento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('stock_min', models.IntegerField()),
                ('stock_max', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('saldo_ini', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('nivel_alerta', models.IntegerField()),
                ('entradas', models.IntegerField()),
                ('salidas', models.IntegerField()),
                ('obsProd', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('obs_movimiento', models.TextField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('obs_Transaccion', models.TextField()),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.documento')),
                ('id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.movimiento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='id_usuario_genera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_generados', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_roles', to='api.roles')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.usuario')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_rol')},
            },
        ),
    ]
