# Generated by Django 4.2.19 on 2025-03-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_cajadiario_clientes_pedido_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo de Django asociado a este rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
