# Generated by Django 4.2.19 on 2025-06-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('en_preparacion', 'En preparación'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='recibido', max_length=50),
        ),
    ]
