name: Deploy to EC2  # Este nombre aparecerá en la pestaña "Actions" de GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          echo "Desplegando..."
          sudo systemctl restart django.service
