name: Deploy to EC2  # Nombre del workflow en GitHub Actions

on:
  push:
    branches:
      - main

concurrency:  # 🔹 Aquí defines la concurrencia para evitar que jobs se acumulen en "Queued"
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]  # Especificar bien el runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Limpiar procesos previos  # 🔹 Detener procesos previos antes de desplegar
        run: |
          sudo systemctl stop django.service || true
          sudo pkill -f django || true

      - name: Deploy application  # 🔹 Reiniciar después de limpiar
        run: |
          echo "Desplegando..."
          sudo systemctl restart django.service
